---
site:
  title: Jenkins Docs
  url: https://docs.jenkins.io
  start_page: user-docs::index.adoc
  robots: allow

content:
  sources:
    - url: https://github.com/jenkins-infra/docs.jenkins.io.git
      branches: [HEAD]
      start_paths: [docs/solutions, docs/tutorials, docs/user-docs]
      # developer docs are un-versioned that's why they're fetched individually
    - url: https://github.com/jenkins-infra/docs.jenkins.io.git
      branches: [HEAD]
      start_paths:
        [
          docs/dev-docs,
          docs/download,
          docs/images,
          docs/project,
          docs/projects,
          docs/security,
          docs/sigs,
        ]
    - url: https://github.com/jenkins-infra/jenkins.io.git
      branches: [HEAD]
      start_paths:
        [
          content/images
        ]

runtime:
  cache_dir: ./.cache/antora
  fetch: true
  log:
    level: error

asciidoc:
  attributes:
    page-pagination: ''
    plugin: 'https://plugins.jenkins.io/'
    jira: 'https://issues.jenkins.io/browse/'
    jep: 'https://github.com/jenkinsci/jep/tree/master/jep/'
    matrix: 'https://matrix.to/#/#'
    email: 'jenkinsci-users@googlegroups.com'
    site-description: 'Official Jenkins documentation: pipelines, plugins, admin guides, tutorials, and best practices.'
    site-twitter: '@jenkinsci'
    site-og-image: '/img/social/og-default.png'
    site-name: 'Jenkins'

ui:
  bundle:
    url: https://raw.githubusercontent.com/jenkins-infra/docs.jenkins.io/main/ui/build/ui-bundle.zip
    snapshot: true
